[package]
name = "imap-codec"
version = "0.1.0"
authors = ["Damian Poddebniak <poddebniak@fh-muenster.de>"]
edition = "2018"

[dependencies]
chrono = "0.4"
nom = "5.1"
serde = { version = "1.0", features = ["derive"] }
abnf-core = "0.3.0"
rand = "*"

[dev-dependencies]
assert_matches = "1.3"
