[package]
name = "imap-codec"
description = "Low-level IMAP Parser and Serializer"
keywords = ["email", "imap", "parser", "codec"]
version = "0.2.1"
authors = ["Damian Poddebniak <poddebniak@fh-muenster.de>"]
repository = "https://github.com/duesee/imap-codec"
license = "MIT OR Apache-2.0"
edition = "2018"

[features]
default = []
serdex  = ["serde", "chrono/serde"]

[dependencies]
chrono = "0.4"
nom = "6"
abnf-core = "0.4"
rand = "0.7.3"

# Optional
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
assert_matches = "1.4"
